// Generated by CoffeeScript 1.6.2
var HipchatExec, Hipchatter, http, path, sh;

http = require('http');

path = require('path');

Hipchatter = require('hipchatter');

sh = require('execSync');

HipchatExec = (function() {
  function HipchatExec(config) {
    var cmd, script, _ref;

    this.commands = {};
    _ref = config.commands;
    for (cmd in _ref) {
      script = _ref[cmd];
      this.commands[cmd] = script;
    }
    this.token = config.token;
    this.frequency = config.frequency;
    this.room = config.room;
    this.hipchatter = new Hipchatter(this.token);
  }

  HipchatExec.prototype.run = function() {
    var self;

    self = this;
    return setInterval((function() {
      return self.pollHipchat();
    }), this.frequency);
  };

  HipchatExec.prototype.pollHipchat = function() {
    return this.hipchatter.history(this.room, function(err, history) {
      if (err != null) {
        return console.error('Hipchat error ' + err);
      } else {
        return console.log(history);
      }
    });
  };

  return HipchatExec;

})();

module.exports = HipchatExec;
