// Generated by CoffeeScript 1.6.2
var HipchatExec, Hipchatter, http, path, sh;

http = require('http');

path = require('path');

Hipchatter = require('hipchatter');

sh = require('execSync');

HipchatExec = (function() {
  function HipchatExec(config) {
    var cmd, script, _ref;

    this.commands = {};
    _ref = config.commands;
    for (cmd in _ref) {
      script = _ref[cmd];
      this.commands[cmd] = script;
    }
    this.token = config.token;
    this.frequency = config.frequency;
    this.room = config.room;
    this.hipchatter = new Hipchatter(this.token);
  }

  HipchatExec.prototype.run = function() {
    var runFunction;

    runFunction = function() {
      return console.log('test');
    };
    return setInterval(runFunction, this.frequency);
  };

  return HipchatExec;

})();

module.exports = HipchatExec;
